import 'package:hat_bazar/Models/Product.dart';

var products = [

Product(
    id: "1",
    name: "Shoe",
    description: "This is a stylish Shoe",
    stock: 23,
    sellPrice: 1200,
    purchasePrice: 1000,
    unit: "Piece",
    unitPrice: 1200,
    category: "Fashion",
    cratedAt: "",
    discount: 0.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["shoe", "Juta"],
    updatedAt: ""
  ),
Product(
    id: "2",
    name: "Sneaker",
    description: "This is a trendy Sneaker",
    stock: 10,
    sellPrice: 1500,
    purchasePrice: 1200,
    unit: "Pair",
    unitPrice: 1500,
    category: "Sports",
    cratedAt: "",
    discount: 10.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["sneaker", "shoe"],
    updatedAt: ""
  ),
Product(
    id: "3",
    name: "Running Shoe",
    description: "Comfortable running shoe",
    stock: 50,
    sellPrice: 1800,
    purchasePrice: 1600,
    unit: "Piece",
    unitPrice: 1800,
    category: "Sports",
    cratedAt: "",
    discount: 5.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["running", "shoe"],
    updatedAt: ""
  ),
Product(
    id: "4",
    name: "Boots",
    description: "Durable leather boots",
    stock: 15,
    sellPrice: 2200,
    purchasePrice: 2000,
    unit: "Piece",
    unitPrice: 2200,
    category: "Fashion",
    cratedAt: "",
    discount: 8.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["boots", "leather"],
    updatedAt: ""
  ),
Product(
    id: "5",
    name: "Flip Flop",
    description: "Comfortable flip flops",
    stock: 100,
    sellPrice: 500,
    purchasePrice: 400,
    unit: "Pair",
    unitPrice: 500,
    category: "Casual",
    cratedAt: "",
    discount: 2.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["flip flop", "sandal"],
    updatedAt: ""
  ),
Product(
    id: "6",
    name: "Formal Shoe",
    description: "Elegant formal shoes",
    stock: 30,
    sellPrice: 2500,
    purchasePrice: 2300,
    unit: "Pair",
    unitPrice: 2500,
    category: "Formal",
    cratedAt: "",
    discount: 12.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["formal", "shoe"],
    updatedAt: ""
  ),
Product(
    id: "7",
    name: "Loafers",
    description: "Comfortable loafers for casual wear",
    stock: 40,
    sellPrice: 1900,
    purchasePrice: 1700,
    unit: "Piece",
    unitPrice: 1900,
    category: "Casual",
    cratedAt: "",
    discount: 7.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["loafers", "shoe"],
    updatedAt: ""
  ),
Product(
    id: "8",
    name: "Heels",
    description: "Stylish high heels",
    stock: 12,
    sellPrice: 2600,
    purchasePrice: 2400,
    unit: "Pair",
    unitPrice: 2600,
    category: "Fashion",
    cratedAt: "",
    discount: 10.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["heels", "fashion"],
    updatedAt: ""
  ),
Product(
    id: "9",
    name: "Slippers",
    description: "Cozy indoor slippers",
    stock: 80,
    sellPrice: 600,
    purchasePrice: 500,
    unit: "Pair",
    unitPrice: 600,
    category: "Casual",
    cratedAt: "",
    discount: 3.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["slippers", "indoor"],
    updatedAt: ""
  ),
Product(
    id: "10",
    name: "Sandals",
    description: "Durable outdoor sandals",
    stock: 60,
    sellPrice: 800,
    purchasePrice: 700,
    unit: "Pair",
    unitPrice: 800,
    category: "Outdoor",
    cratedAt: "",
    discount: 5.0,
    discountEndDate: "",
    discountStartDate: "",
    images: [
      "https://firebasestorage.googleapis.com/v0/b/chat-app-demo-ef05c.appspot.com/o/Uploads%2Fshoe.jpg?alt=media&token=1ac7de81-f102-4e00-99e9-de6997ec12ed"
    ],
    isActive: true,
    reviews: [],
    supplier: "Mipon Rahman",
    tags: ["sandals", "outdoor"],
    updatedAt: ""
  ),

];
