// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmuMplp-wno_chYvPh7_7Z_1V_gehYmHk',
    appId: '1:488045321617:web:4d7834f9c8b91cebc58e30',
    messagingSenderId: '488045321617',
    projectId: 'hat-bazar-e-commerce',
    authDomain: 'hat-bazar-e-commerce.firebaseapp.com',
    storageBucket: 'hat-bazar-e-commerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEiLT9V_Ugf812vzwZoyBxVC5qUkBrQYs',
    appId: '1:488045321617:android:064f17c70133793ec58e30',
    messagingSenderId: '488045321617',
    projectId: 'hat-bazar-e-commerce',
    storageBucket: 'hat-bazar-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADq_XtABXCyWWdhJhJJ1f8lRFe8SBPpcU',
    appId: '1:488045321617:ios:ee819748a44401ecc58e30',
    messagingSenderId: '488045321617',
    projectId: 'hat-bazar-e-commerce',
    storageBucket: 'hat-bazar-e-commerce.appspot.com',
    iosBundleId: 'com.hatbazar.admin.hatBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADq_XtABXCyWWdhJhJJ1f8lRFe8SBPpcU',
    appId: '1:488045321617:ios:ee819748a44401ecc58e30',
    messagingSenderId: '488045321617',
    projectId: 'hat-bazar-e-commerce',
    storageBucket: 'hat-bazar-e-commerce.appspot.com',
    iosBundleId: 'com.hatbazar.admin.hatBazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmuMplp-wno_chYvPh7_7Z_1V_gehYmHk',
    appId: '1:488045321617:web:531c1d10f1054f94c58e30',
    messagingSenderId: '488045321617',
    projectId: 'hat-bazar-e-commerce',
    authDomain: 'hat-bazar-e-commerce.firebaseapp.com',
    storageBucket: 'hat-bazar-e-commerce.appspot.com',
  );
}
